# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_cards2',
                'doc_host': 'https://cduguet.github.io',
                'git_url': 'https://github.com/cduguet/nbdev_cards2',
                'lib_path': 'nbdev_cards2'},
  'syms': {'nbdev_cards2.core': {'nbdev_cards2.core.foo': ('core.html#foo', 'nbdev_cards2/core.py')}}}
