# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_cards2',
                'doc_host': 'https://cduguet.github.io',
                'git_url': 'https://github.com/cduguet/nbdev_cards2',
                'lib_path': 'nbdev_cards2'},
  'syms': { 'nbdev_cards2.card': { 'nbdev_cards2.card.Card': ('card.html#card', 'nbdev_cards2/card.py'),
                                   'nbdev_cards2.card.Card.__eq__': ('card.html#card.__eq__', 'nbdev_cards2/card.py'),
                                   'nbdev_cards2.card.Card.__gt__': ('card.html#card.__gt__', 'nbdev_cards2/card.py'),
                                   'nbdev_cards2.card.Card.__init__': ('card.html#card.__init__', 'nbdev_cards2/card.py'),
                                   'nbdev_cards2.card.Card.__lt__': ('card.html#card.__lt__', 'nbdev_cards2/card.py'),
                                   'nbdev_cards2.card.Card.__repr__': ('card.html#card.__repr__', 'nbdev_cards2/card.py')},
            'nbdev_cards2.deck': {'nbdev_cards2.deck.Deck': ('deck.html#deck', 'nbdev_cards2/deck.py')}}}
