# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_cards.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../nbs/00_cards.ipynb 3
suits = "♠ ♥ ♦ ♣".split()
ranks = [None] + "A 2 3 4 5 6 7 8 9 10 J Q K".split()

# %% ../nbs/00_cards.ipynb 12
class Card:
    "A playing card."
    def __init__(self, 
                suit:int, # A number representing the suit (0-3)
                rank:int): # A number representing the rank (1-13)
        self.suit = suit
        self.rank = rank

    def __repr__(self):
        return f"{ranks[self.rank]}{suits[self.suit]}"
    
    __str__ = __repr__
