# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_deck.ipynb.

# %% auto 0
__all__ = ['Deck']

# %% ../nbs/01_deck.ipynb 3
from fastcore.utils import *

# %% ../nbs/01_deck.ipynb 4
from .card import *

# %% ../nbs/01_deck.ipynb 5
class Deck:
    pass
